steps:
  - id: install-next-app
    name: node:16
    dir: app
    entrypoint: npm
    args: ['ci']

  - id: build-app-image
    name: 'gcr.io/cloud-builders/docker'
    dir: app
    args:
      [
        'build',
        '-t',
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_APP_NAME}:$COMMIT_SHA',
        '.'
      ]

  - id: push-image-to-registry
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_APP_NAME}:$COMMIT_SHA']

  - id: deploy-image-to-cloudrun
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_APP_NAME}:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--ingress'
      - 'internal-and-cloud-load-balancing'
      - '--update-secrets'
      - 'DATABASE_URL=tanuki-database-url:latest'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_APP_NAME}:$COMMIT_SHA'

timeout: 1200s
