steps:
  - id: install-next-app
    name: node:16
    dir: app
    entrypoint: npm
    args: ['ci']

  - id: test-next-app
    name: node:16
    dir: app
    entrypoint: npm
    args: ['run', 'test:ci']
    waitFor: ['install-next-app']

  - id: build-next-app
    name: node:16
    dir: app
    entrypoint: npm
    args: ['run', 'build']
    waitFor: ['install-next-app']
