version: '3.7'
services:
  mongo:
    image: mongo:4
    command: --replSet rs0
    ports:
      - '27017:27017'
      - '28017:28017'
    volumes:
      - ./local_mongo/rs-initiate.js:/docker-entrypoint-initdb.d/rs-initiate.js
      - ./local_mongo/data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=tanuki_dev
